name: github_search_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Networking client (For API Calls)
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0

  # Dependency Injection
  get_it: ^8.0.3

  # A library that checks for internet by opening a socket to a list of specified addresses
  internet_connection_checker_plus: ^2.7.1

  # Bloc State Management
  flutter_bloc: ^9.1.0

  # Caching Helper for images
  cached_network_image: ^3.4.1

  # Shimmer Effect for loading
  skeletonizer: ^1.4.3

  # Caching Helper for usual Data
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Generate Icons & Splash Screen
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
